name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Test, Clippy, Shear, Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install cargo-shear
        uses: cargo-bins/cargo-binstall@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: cargo test
        run: cargo test

      - name: cargo clippy
        run: cargo clippy --no-deps -- -D warnings

      - name: cargo shear
        run: cargo shear

      - name: cargo fmt
        run: cargo fmt -- --check
